### PR TITLE
Treeview: Fixed icons on dark themes

### LINKED ISSUE #2630: Treeview's icons are not visible in dark theme
**Information:**
- Prism version: **1.22**
- Plugins: **Treeview**
- Environment: **All Browser**

**Description**  
Treeview's icons fill color is `#000`, it makes them invisible in dark themes. 

**Example**  
At [Treeview](https://prismjs.com/plugins/treeview/) page, using the **dark** theme or **funky** theme, then we can see that.

**Fixed**  
I have provided an improved scheme. First, the encoding mode of SVG file will be improved to make the file smaller and the code can be read. Secondly, add the `fill` attribute to the `<path>`  and change the color to `#999`. In this way, the icon can be visible in all the themes. Here is the result compare : 
Prism-Treeview-Debug

<details>
	<summary>Click to expand the code</summary>
	
```css
.token.treeview-part .entry-name:before{background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='179.2' width='179.2'%3E%3Cpath fill='%23999' d='M146.8 38q2.8 2.8 4.8 7.6t2 8.8v115.2q0 4-2.8 6.8t-6.8 2.8H9.6q-4 0-6.8-2.8T0 169.6V9.6q0-4 2.8-6.8T9.6 0h89.6q4 0 8.8 2t7.6 4.8zm-44.4-24.4v37.6H140q-1-2.9-2.2-4.1l-31.3-31.3q-1.2-1.2-4.1-2.2zm38.4 152.8V64H99.2q-4 0-6.8-2.8t-2.8-6.8V12.8H12.8v153.6h128z'/%3E%3C/svg%3E");}

.token.treeview-part .entry-name.dir:before{background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='179.2' width='179.2'%3E%3Cpath fill='%23999' d='M153.6 131.2V60.8q0-4-2.8-6.8t-6.8-2.8H73.6q-4 0-6.8-2.8T64 41.6v-6.4q0-4-2.8-6.8t-6.8-2.8h-32q-4 0-6.8 2.8t-2.8 6.8v96q0 4 2.8 6.8t6.8 2.8H144q4 0 6.8-2.8t2.8-6.8zm12.8-70.4v70.4q0 9.2-6.6 15.8t-15.8 6.6H22.4q-9.2 0-15.8-6.6T0 131.2v-96Q0 26 6.6 19.4t15.8-6.6h32q9.2 0 15.8 6.6t6.6 15.8v3.2H144q9.2 0 15.8 6.6t6.6 15.8z'/%3E%3C/svg%3E");}

.token.treeview-part .entry-name.ext-bmp:before, 
.token.treeview-part .entry-name.ext-eps:before, 
.token.treeview-part .entry-name.ext-gif:before, 
.token.treeview-part .entry-name.ext-jpe:before, 
.token.treeview-part .entry-name.ext-jpg:before, 
.token.treeview-part .entry-name.ext-jpeg:before, 
.token.treeview-part .entry-name.ext-png:before, 
.token.treeview-part .entry-name.ext-svg:before, 
.token.treeview-part .entry-name.ext-tiff:before{background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='179.2' width='179.2'%3E%3Cpath fill='%23999' d='M146.8 38q2.8 2.8 4.8 7.6t2 8.8v115.2q0 4-2.8 6.8t-6.8 2.8H9.6q-4 0-6.8-2.8T0 169.6V9.6q0-4 2.8-6.8T9.6 0h89.6q4 0 8.8 2t7.6 4.8zm-44.4-24.4v37.6H140q-1-2.9-2.2-4.1l-31.3-31.3q-1.2-1.2-4.1-2.2zm38.4 152.8V64H99.2q-4 0-6.8-2.8t-2.8-6.8V12.8H12.8v153.6h128zM128 121.6v32H25.6v-19.2l19.2-19.2L57.6 128 96 89.6zm-83.2-19.2q-8 0-13.6-5.6t-5.6-13.6 5.6-13.6T44.8 64t13.6 5.6T64 83.2t-5.6 13.6-13.6 5.6z'/%3E%3C/svg%3E");}

.token.treeview-part .entry-name.ext-cfg:before, 
.token.treeview-part .entry-name.ext-conf:before, 
.token.treeview-part .entry-name.ext-config:before, 
.token.treeview-part .entry-name.ext-csv:before, 
.token.treeview-part .entry-name.ext-ini:before, 
.token.treeview-part .entry-name.ext-log:before, 
.token.treeview-part .entry-name.ext-md:before, 
.token.treeview-part .entry-name.ext-nfo:before, 
.token.treeview-part .entry-name.ext-txt:before{background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='179.2' width='179.2'%3E%3Cpath fill='%23999' d='M146.8 38q2.8 2.8 4.8 7.6t2 8.8v115.2q0 4-2.8 6.8t-6.8 2.8H9.6q-4 0-6.8-2.8T0 169.6V9.6q0-4 2.8-6.8T9.6 0h89.6q4 0 8.8 2t7.6 4.8zm-44.4-24.4v37.6H140q-1-2.9-2.2-4.1l-31.3-31.3q-1.2-1.2-4.1-2.2zm38.4 152.8V64H99.2q-4 0-6.8-2.8t-2.8-6.8V12.8H12.8v153.6h128zM38.4 80q0-1.4.9-2.3t2.3-.9H112q1.4 0 2.3.9t.9 2.3v6.4q0 1.4-.9 2.3t-2.3.9H41.6q-1.4 0-2.3-.9t-.9-2.3V80zm73.6 22.4q1.4 0 2.3.9t.9 2.3v6.4q0 1.4-.9 2.3t-2.3.9H41.6q-1.4 0-2.3-.9t-.9-2.3v-6.4q0-1.4.9-2.3t2.3-.9H112zm0 25.6q1.4 0 2.3.9t.9 2.3v6.4q0 1.4-.9 2.3t-2.3.9H41.6q-1.4 0-2.3-.9t-.9-2.3v-6.4q0-1.4.9-2.3t2.3-.9H112z'/%3E%3C/svg%3E");}

.token.treeview-part .entry-name.ext-asp:before, 
.token.treeview-part .entry-name.ext-aspx:before, 
.token.treeview-part .entry-name.ext-c:before, 
.token.treeview-part .entry-name.ext-cc:before, 
.token.treeview-part .entry-name.ext-cpp:before, 
.token.treeview-part .entry-name.ext-cs:before, 
.token.treeview-part .entry-name.ext-css:before, 
.token.treeview-part .entry-name.ext-h:before, 
.token.treeview-part .entry-name.ext-hh:before, 
.token.treeview-part .entry-name.ext-htm:before, 
.token.treeview-part .entry-name.ext-html:before, 
.token.treeview-part .entry-name.ext-jav:before, 
.token.treeview-part .entry-name.ext-java:before, 
.token.treeview-part .entry-name.ext-js:before, 
.token.treeview-part .entry-name.ext-php:before, 
.token.treeview-part .entry-name.ext-rb:before, 
.token.treeview-part .entry-name.ext-xml:before{background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='179.2' width='179.2'%3E%3Cpath fill='%23999' d='M146.8 38q2.8 2.8 4.8 7.6t2 8.8v115.2q0 4-2.8 6.8t-6.8 2.8H9.6q-4 0-6.8-2.8T0 169.6V9.6q0-4 2.8-6.8T9.6 0h89.6q4 0 8.8 2t7.6 4.8zm-44.4-24.4v37.6H140q-1-2.9-2.2-4.1l-31.3-31.3q-1.2-1.2-4.1-2.2zm38.4 152.8V64H99.2q-4 0-6.8-2.8t-2.8-6.8V12.8H12.8v153.6h128zM48 76.8q.8-1.1 2.1-1.25t2.4.65l5.1 3.8q1.1.8 1.25 2.1t-.65 2.4L40 108.8l18.2 24.3q.8 1.1.65 2.4t-1.25 2.1l-5.1 3.8q-1.1.8-2.4.65T48 140.8l-22.6-30.1q-1.4-1.9 0-3.8zm80.2 30.1q1.4 1.9 0 3.8l-22.6 30.1q-.8 1.1-2.1 1.25t-2.4-.65l-5.1-3.8q-1.1-.8-1.25-2.1t.65-2.4l18.2-24.3-18.2-24.3q-.8-1.1-.65-2.4T96 80l5.1-3.8q1.1-.8 2.4-.65t2.1 1.25zm-62 46.1q-1.3-.2-2.05-1.3t-.55-2.4l13.8-83.1q.2-1.3 1.3-2.05t2.4-.55l6.3 1q1.3.2 2.05 1.3t.55 2.4l-13.8 83.1q-.2 1.3-1.3 2.05t-2.4.55z'/%3E%3C/svg%3E");}

.token.treeview-part .entry-name.ext-7z:before, 
.token.treeview-part .entry-name.ext-bz:before, 
.token.treeview-part .entry-name.ext-bz2:before, 
.token.treeview-part .entry-name.ext-gz:before, 
.token.treeview-part .entry-name.ext-rar:before, 
.token.treeview-part .entry-name.ext-tar:before, 
.token.treeview-part .entry-name.ext-tgz:before, 
.token.treeview-part .entry-name.ext-zip:before{background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='179.2' width='179.2'%3E%3Cpath fill='%23999' d='M64 38.4V25.6H51.2v12.8H64zm12.8 12.8V38.4H64v12.8h12.8zM64 64V51.2H51.2V64H64zm12.8 12.8V64H64v12.8h12.8zm70-38.8q2.8 2.8 4.8 7.6t2 8.8v115.2q0 4-2.8 6.8t-6.8 2.8H9.6q-4 0-6.8-2.8T0 169.6V9.6q0-4 2.8-6.8T9.6 0h89.6q4 0 8.8 2t7.6 4.8zm-44.4-24.4v37.6H140q-1-2.9-2.2-4.1l-31.3-31.3q-1.2-1.2-4.1-2.2zm38.4 152.8V64H99.2q-4 0-6.8-2.8t-2.8-6.8V12.8H76.8v12.8H64V12.8H12.8v153.6h128zM78.1 94.3l10.7 34.9q.8 2.7.8 5.2 0 8.3-7.25 13.75T64 153.6t-18.35-5.45-7.25-13.75q0-2.5.8-5.2 2.1-6.3 12-39.6V76.8H64v12.8h7.9q2.2 0 3.9 1.3t2.3 3.4zM64 140.8q5.3 0 9.05-1.9t3.75-4.5-3.75-4.5T64 128t-9.05 1.9-3.75 4.5 3.75 4.5 9.05 1.9z'/%3E%3C/svg%3E");}

.token.treeview-part .entry-name.ext-aac:before, 
.token.treeview-part .entry-name.ext-au:before, 
.token.treeview-part .entry-name.ext-cda:before, 
.token.treeview-part .entry-name.ext-flac:before, 
.token.treeview-part .entry-name.ext-mp3:before, 
.token.treeview-part .entry-name.ext-oga:before, 
.token.treeview-part .entry-name.ext-ogg:before, 
.token.treeview-part .entry-name.ext-wav:before, 
.token.treeview-part .entry-name.ext-wma:before{background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='179.2' width='179.2'%3E%3Cpath fill='%23999' d='M146.8 38q2.8 2.8 4.8 7.6t2 8.8v115.2q0 4-2.8 6.8t-6.8 2.8H9.6q-4 0-6.8-2.8T0 169.6V9.6q0-4 2.8-6.8T9.6 0h89.6q4 0 8.8 2t7.6 4.8zm-44.4-24.4v37.6H140q-1-2.9-2.2-4.1l-31.3-31.3q-1.2-1.2-4.1-2.2zm38.4 152.8V64H99.2q-4 0-6.8-2.8t-2.8-6.8V12.8H12.8v153.6h128zM62 85q2 .8 2 3v54.4q0 2.2-2 3-.8.2-1.2.2-1.2 0-2.3-.9L41.9 128H28.8q-1.4 0-2.3-.9t-.9-2.3v-19.2q0-1.4.9-2.3t2.3-.9h13.1l16.6-16.7q1.6-1.5 3.5-.7zm41.7 68.9q3.1 0 5-2.4 12.9-15.9 12.9-36.3t-12.9-36.3q-1.6-2.1-4.3-2.4t-4.7 1.4q-2.1 1.7-2.35 4.35T98.8 87q10 12.3 10 28.2t-10 28.2q-1.7 2.1-1.45 4.75t2.35 4.25q1.8 1.5 4 1.5zm-21.1-14.8q2.7 0 4.7-2 8.7-9.3 8.7-21.9t-8.7-21.9q-1.8-1.9-4.5-2T78.2 93t-2 4.45 1.8 4.65q5.2 5.7 5.2 13.1T78 128.3q-1.9 2-1.8 4.65t2 4.45q2 1.7 4.4 1.7z'/%3E%3C/svg%3E");}

.token.treeview-part .entry-name.ext-avi:before, 
.token.treeview-part .entry-name.ext-flv:before, 
.token.treeview-part .entry-name.ext-mkv:before, 
.token.treeview-part .entry-name.ext-mov:before, 
.token.treeview-part .entry-name.ext-mp4:before, 
.token.treeview-part .entry-name.ext-mpeg:before, 
.token.treeview-part .entry-name.ext-mpg:before, 
.token.treeview-part .entry-name.ext-ogv:before, 
.token.treeview-part .entry-name.ext-webm:before{background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='179.2' width='179.2'%3E%3Cpath fill='%23999' d='M146.8 38q2.8 2.8 4.8 7.6t2 8.8v115.2q0 4-2.8 6.8t-6.8 2.8H9.6q-4 0-6.8-2.8T0 169.6V9.6q0-4 2.8-6.8T9.6 0h89.6q4 0 8.8 2t7.6 4.8zm-44.4-24.4v37.6H140q-1-2.9-2.2-4.1l-31.3-31.3q-1.2-1.2-4.1-2.2zm38.4 152.8V64H99.2q-4 0-6.8-2.8t-2.8-6.8V12.8H12.8v153.6h128zm-64-89.6q5.2 0 9 3.8t3.8 9V128q0 5.2-3.8 9t-9 3.8H38.4q-5.2 0-9-3.8t-3.8-9V89.6q0-5.2 3.8-9t9-3.8h38.4zm49.2.2q2 .8 2 3v57.6q0 2.2-2 3-.8.2-1.2.2-1.4 0-2.3-.9L96 113.3v-9l26.5-26.6q.9-.9 2.3-.9.4 0 1.2.2z'/%3E%3C/svg%3E");}

.token.treeview-part .entry-name.ext-pdf:before{background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='179.2' width='179.2'%3E%3Cpath fill='%23999' d='M146.8 38q2.8 2.8 4.8 7.6t2 8.8v115.2q0 4-2.8 6.8t-6.8 2.8H9.6q-4 0-6.8-2.8T0 169.6V9.6q0-4 2.8-6.8T9.6 0h89.6q4 0 8.8 2t7.6 4.8zm-44.4-24.4v37.6H140q-1-2.9-2.2-4.1l-31.3-31.3q-1.2-1.2-4.1-2.2zm38.4 152.8V64H99.2q-4 0-6.8-2.8t-2.8-6.8V12.8H12.8v153.6h128zm-51.4-59.3q3.3 2.6 8.4 5.6 5.9-.7 11.7-.7 14.7 0 17.7 4.9 1.6 2.2.2 5.2 0 .1-.1.2l-.2.2v.1q-.6 3.8-7.1 3.8-4.8 0-11.5-2t-13-5.3q-22.1 2.4-39.2 8.3-15.3 26.2-24.2 26.2-1.5 0-2.8-.7l-2.4-1.2q-.1-.1-.6-.5-1-1-.6-3.6.9-4 5.6-9.15t13.2-9.65q1.4-.9 2.3.6.2.2.2.4 5.2-8.5 10.7-19.7 6.8-13.6 10.4-26.2-2.4-8.2-3.05-15.95t.65-12.75q1.1-4 4.2-4h2.2q2.3 0 3.5 1.5 1.8 2.1.9 6.8-.2.6-.4.8.1.3.1.8v3q-.2 12.3-1.4 19.2 5.5 16.4 14.6 23.8zm-57.6 41.1q5.2-2.4 13.7-15.8-5.1 4-8.75 8.4t-4.95 7.4zm39.8-92q-1.5 4.2-.2 13.2.1-.7.7-4.4 0-.3.7-4.3.1-.4.4-.8-.1-.1-.1-.2t-.05-.15-.05-.15q-.1-2.2-1.3-3.6 0 .1-.1.2v.2zm-12.4 66.1q13.5-5.4 28.4-8.1-.2-.1-1.3-.95t-1.6-1.35q-7.6-6.7-12.7-17.6-2.7 8.6-8.3 19.7-3 5.6-4.5 8.3zm64.6-1.6q-2.4-2.4-14-2.4 7.6 2.8 12.4 2.8 1.4 0 1.8-.1 0-.1-.2-.3z'/%3E%3C/svg%3E");}

.token.treeview-part .entry-name.ext-xls:before, 
.token.treeview-part .entry-name.ext-xlsx:before{background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='179.2' width='179.2'%3E%3Cpath fill='%23999' d='M146.8 38q2.8 2.8 4.8 7.6t2 8.8v115.2q0 4-2.8 6.8t-6.8 2.8H9.6q-4 0-6.8-2.8T0 169.6V9.6q0-4 2.8-6.8T9.6 0h89.6q4 0 8.8 2t7.6 4.8zm-44.4-24.4v37.6H140q-1-2.9-2.2-4.1l-31.3-31.3q-1.2-1.2-4.1-2.2zm38.4 152.8V64H99.2q-4 0-6.8-2.8t-2.8-6.8V12.8H12.8v153.6h128zM42.9 143v10.6H71V143h-7.5l10.3-16.1q.5-.7 1-1.65t.75-1.35.35-.4h.2q.1.4.5 1 .2.4.45.75t.6.8.65.85L89 143h-7.6v10.6h29.1V143h-6.8l-19.2-27.3L104 87.5h6.7V76.8H82.8v10.7h7.4l-10.3 15.9q-.4.7-1 1.65t-.9 1.35l-.2.3h-.2q-.1-.4-.5-1-.6-1.1-1.7-2.3L64.8 87.5h7.6V76.8h-29v10.7h6.8l18.9 27.2L49.7 143h-6.8z'/%3E%3C/svg%3E");}

.token.treeview-part .entry-name.ext-doc:before, 
.token.treeview-part .entry-name.ext-docm:before, 
.token.treeview-part .entry-name.ext-docx:before{background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='179.2' width='179.2'%3E%3Cpath fill='%23999' d='M146.8 38q2.8 2.8 4.8 7.6t2 8.8v115.2q0 4-2.8 6.8t-6.8 2.8H9.6q-4 0-6.8-2.8T0 169.6V9.6q0-4 2.8-6.8T9.6 0h89.6q4 0 8.8 2t7.6 4.8zm-44.4-24.4v37.6H140q-1-2.9-2.2-4.1l-31.3-31.3q-1.2-1.2-4.1-2.2zm38.4 152.8V64H99.2q-4 0-6.8-2.8t-2.8-6.8V12.8H12.8v153.6h128zM23.3 76.8v10.7h7l16.4 66.1h15.9l12.8-48.5q.7-2 1-4.6.2-1.6.2-2.4h.4l.3 2.4q.1.3.35 2t.55 2.6L91 153.6h15.9l16.4-66.1h7V76.8h-30v10.7h9l-9.9 43.8q-.5 2-.7 4.6l-.2 2.1h-.4l-.3-2.1q-.1-.5-.4-2.1t-.5-2.5L82.5 76.8H71.1l-14.4 54.5q-.2.9-.45 2.45t-.35 2.15l-.4 2.1h-.4l-.2-2.1q-.2-2.6-.7-4.6l-9.9-43.8h9V76.8h-30z'/%3E%3C/svg%3E");}

.token.treeview-part .entry-name.ext-pps:before, 
.token.treeview-part .entry-name.ext-ppt:before, 
.token.treeview-part .entry-name.ext-pptx:before{background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' height='179.2' width='179.2'%3E%3Cpath fill='%23999' d='M146.8 38q2.8 2.8 4.8 7.6t2 8.8v115.2q0 4-2.8 6.8t-6.8 2.8H9.6q-4 0-6.8-2.8T0 169.6V9.6q0-4 2.8-6.8T9.6 0h89.6q4 0 8.8 2t7.6 4.8zm-44.4-24.4v37.6H140q-1-2.9-2.2-4.1l-31.3-31.3q-1.2-1.2-4.1-2.2zm38.4 152.8V64H99.2q-4 0-6.8-2.8t-2.8-6.8V12.8H12.8v153.6h128zM41.6 143v10.6h32.7V143H65v-16.7h13.7q7.6 0 11.8-1.5 6.7-2.3 10.65-8.7t3.95-14.6q0-8.1-3.7-14.1t-10-8.7q-4.8-1.9-13-1.9H41.6v10.7h9.2V143h-9.2zm35.3-28H65V88.2h12q5.2 0 8.3 1.8 5.6 3.3 5.6 11.5 0 8.9-6.2 12-3.1 1.5-7.8 1.5z'/%3E%3C/svg%3E");}
```
</details>

### PR DESCRIPTION
**Pull request by RunDevelopment**
This fixes #2630.

~I also minified the SVGs themselves. (Hard to see with the base64 thou).~

After [this brilliant idea](https://github.com/PrismJS/prism/issues/2630#issuecomment-726128463) by @xjArea, I changed Treeview's styles to use an icon font. All formerly base64-encoded icons were extracted into a new `plugins/treeview/icons` folder. The extracted SVGs are both optimized and formatted.

The WOFF icon font is automatically generated using [webfont](https://github.com/itgalaxy/webfont). The build process will then automatically inline the font into the `prism-treeview.css` file as a `@font-face` rule along with an explanation on how to use the font.

This also decreases the file size of the CSS file, from 18KB down to 8KB.

Tested for Chrome 86, FF 81, and IE11.

### CODE REVIEW

File: gulpfile.js/changelog.js [hunk 1]
```diff
@@ -100,14 +100,16 @@ async function getLog(range) {
 }
 
 const revisionRanges = {
-	nextRelease: git.raw(['describe', '--abbrev=0', '--tags']).then(res => `${res.trim()}..HEAD`)
```
Comment (RunDevelopment) [inline gulpfile.js/changelog.js:103]: I have no idea why but this crashed the build with a

```
fatal: No names found, cannot describe anything.
``` 

No other information given. 

It worked before, so my guess is that either GH made a slight change to how PRs are setup on workflows or that webfont or one of its dependencies messes with git in some way. This problem doesn't occur locally.

No idea what the error is or why it happened but I fixed it.

**Review by mAAdhaTTah — APPROVED** [review]
LOVE this!
