### PR TITLE
gulp: Split gulpfile.js and expanded `changes` task

### LINKED ISSUE #1392: Module attributes in Elixir lead to an error
When using [module attributes in Elixir](https://elixir-lang.org/getting-started/module-attributes.html) the closing bracket isn't tokenized as punctuation 
screen shot 2018-04-15 at 12 39 03

Example Code:

```elixir
defmodule BrakeBracketPairColorizer do
  @fixed "foo"

  def foobar() do
    foo = String.upcase(@fixed)
                              ^ Missing punctuation
    foo <> "BAR"
  end
end

```

### LINKED ISSUE #1397: Javascript syntax highlighting for template string nesting doesn't work
Nesting within a template string does not work correctly, it portrays the first backtick as ending the outside template string and the second one as starting a new template string, for example:

`` Prism.highlight('`${`a string`}`', Prism.languages.javascript, 'javascript') ``

This should produce the following:

```html
<pre>
  <code id="ncode">
    <span class="token template-string">
      <span class="token string">`</span>
      <span class="token interpolation">
        <span class="token interpolation-punctuation punctuation">${</span>
        <span class="token template-string">
          <span class="token string">`a string`</span>
        </span>
        <span class="token interpolation-punctuation punctuation">}</span>
      </span>
      <span class="token string">`</span>
    </span>
  </code>
</pre>
```

But instead it produces this:
```html
<pre>
  <code id="code">
    <span class="token template-string">
      <span class="token string">`${`</span>
    </span>
      a string
    <span class="token template-string">
      <span class="token string">`}`</span>
    </span>
  </code>
</pre>
```

### LINKED ISSUE #1405: XQuery language support
I do a lot of work with the XQuery language, and would like to see support for it in PrismJS.

Documentation:
* [W3C XQuery Standards](https://www.w3.org/standards/techs/xquery)
* [XQuery examples from the XQuery book](http://www.datypic.com/books/xquery/appendixa.html)
* [Highlight.js XQuery definition, could provide a quick cheat sheet](https://github.com/isagalaev/highlight.js/blob/master/src/languages/xquery.js)

### LINKED ISSUE #1407: Powershell nested expressions missing punctuation
```
While($true){
    Write-Output "$($($InFiles | Where-Object {$_.ToCopy -eq 0}).count)"
                                                                      ^ Missing punctuation
}
```

Token output:
```
_.Token {type: "string", content: Array(3), alias: undefined, …}
alias:undefined
content:Array(3) [""", _.Token, ".count)""]
length:3
__proto__:Array(0) [, …]
0:"""
1:_.Token {type: "function", content: Array(18), alias: undefined, …}
2:".count)""
greedy:true
length:55
type:"string"
__proto__:Object {constructor: }
```

### LINKED ISSUE #1408: JSX tag is not recognized when there's template string in attribute
For example, below jsx tag is not recognized:
```
<div style={{ marginLeft: `${sidePanelWidth}px` }}>
```

### LINKED ISSUE #1421: JSX fragments short syntax is not supported
Like below code:
```javascript
class Columns extends React.Component {
  render() {
    return (
      <>
        <td>Hello</td>
        <td>World</td>
      </>
    );
  }
}
```
See more about React fragments: https://reactjs.org/docs/fragments.html

### PR DESCRIPTION
**Pull request by RunDevelopment**
This PR [splits the `gulpfile.js`](https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles#splitting-a-gulpfile) into different parts.

I also completely rewrote the `changes` task to generate a mostly ready changelog.
It automatically assigns a category to commits based on the files changed by a commit. This only includes a few trivial cases where the category is clear; All other commits get the `TODO:` category.
'Rebuild commits' (commits where only generated files change) get ignored but a message will be logged just in case.

Note: Careful review of the generated changelog is still necessary.

Here are a few examples of the outputs of `gulp changes` for different commit ranges:

The default range is `<currentVersionTag>..HEAD`, but it's easy to specify a different range.

<details>
<summary><code>v1.14.0..v1.15.0</code></summary>

```markdown
Rebuild found: Update minified files
Rebuild found: Run gulp
Rebuild found: Run gulp

### TODO:

* 1.15.0 [`7d084d5f`](https://github.com/PrismJS/prism/commit/7d084d5f)
* Merge pull request #1440 from PrismJS/fix-solidity-protocol [`5f04f4d4`](https://github.com/PrismJS/prism/commit/5f04f4d4)
* Merge pull request #1430 from PrismJS/add-tap [`09b56af2`](https://github.com/PrismJS/prism/commit/09b56af2)
* Fix Swift protocol test [`2c6b6a42`](https://github.com/PrismJS/prism/commit/2c6b6a42)
* Merge branch 'gh-pages' [`15957702`](https://github.com/PrismJS/prism/commit/15957702)
* Merge pull request #1437 from ilaborie/patch-1 [`c8c52071`](https://github.com/PrismJS/prism/commit/c8c52071)
* Merge pull request #1434 from PrismJS/fix-line-numbers-specificity [`03e8d9cc`](https://github.com/PrismJS/prism/commit/03e8d9cc)
* Merge pull request #1255 from teroauralinna/gh-pages [`6584d5bb`](https://github.com/PrismJS/prism/commit/6584d5bb)
* Merge remote-tracking branch 'upstream/gh-pages' into gh-pages [`d6e064d1`](https://github.com/PrismJS/prism/commit/d6e064d1)
* Make line-numbers styles more specific [`9ee4f547`](https://github.com/PrismJS/prism/commit/9ee4f547)
* Merge pull request #1429 from PrismJS/docs/webpack-and-node [`2d3d380b`](https://github.com/PrismJS/prism/commit/2d3d380b)
* Handle optional dependencies in `loadLanguages()` (#1417) [`84935acd`](https://github.com/PrismJS/prism/commit/84935acd)
* Website: Fix Download page not handling multiple dependencies when from Redownload URL [`c2ff2482`](https://github.com/PrismJS/prism/commit/c2ff2482)
* ASP.NET should require C# [`fa328bb1`](https://github.com/PrismJS/prism/commit/fa328bb1)
* Merge pull request #1410 from jwworth/add-language-guard [`68d3c48e`](https://github.com/PrismJS/prism/commit/68d3c48e)
* Add missing reference to issue in specific test. [`a349c0cd`](https://github.com/PrismJS/prism/commit/a349c0cd)
* Use HTTPS / canonical URLs (#1390) [`95146c8f`](https://github.com/PrismJS/prism/commit/95146c8f)

### New components

* __TAP__: Add TAP component [`8c2b71f1`](https://github.com/PrismJS/prism/commit/8c2b71f1)
* __Template Toolkit 2__: Support for Template Toolkit 2 (#1418) [`e063992b`](https://github.com/PrismJS/prism/commit/e063992b)
* __XQuery__: Add support for XQuery. Fix #1405 (#1411) [`e326cb03`](https://github.com/PrismJS/prism/commit/e326cb03)

### Updated components

* __Bash__
    * Change reserved keyword reference (#1396) [`b94f01f1`](https://github.com/PrismJS/prism/commit/b94f01f1)
* __Elixir__
    * Elixir: Fix attributes consuming punctuation. Fix #1392 [`dac0485e`](https://github.com/PrismJS/prism/commit/dac0485e)
* __HTTP__
    * HTTP: Absolute path is a valid request uri (#1388) [`f6e81cb4`](https://github.com/PrismJS/prism/commit/f6e81cb4)
* __JavaScript__
    * JavaScript: Add support for one level of nesting inside template strings. Fix #1397 [`db2d0ebb`](https://github.com/PrismJS/prism/commit/db2d0ebb)
    * JavaScript: Improve Regexp pattern [`5b043cf8`](https://github.com/PrismJS/prism/commit/5b043cf8)
* __Kotlin__
    * Kotlin: add `typealias` keyword [`a21fdee6`](https://github.com/PrismJS/prism/commit/a21fdee6)
    * Add keywords of Kotlin and modify it's number pattern. (#1389) [`1bf73b0b`](https://github.com/PrismJS/prism/commit/1bf73b0b)
* __Pascal__
    * Add `objectpascal` as an alias to `pascal` (see #1426) [`a0bfc84d`](https://github.com/PrismJS/prism/commit/a0bfc84d)
* __PowerShell__
    * Powershell: Allow for one level of nesting in expressions inside strings. Fix #1407 [`9272d6f4`](https://github.com/PrismJS/prism/commit/9272d6f4)
* __React JSX__
    * JSX: Add support for fragments short syntax. Fix #1421 [`38ce1213`](https://github.com/PrismJS/prism/commit/38ce1213)
    * JSX: Allow for two levels of nesting inside JSX tags. Fix #1408 [`f1cd7c56`](https://github.com/PrismJS/prism/commit/f1cd7c56)
* __Swift__
    * Fix Swift 'protocol' keyword [`081e318c`](https://github.com/PrismJS/prism/commit/081e318c)
* __TAP__
    * Add tests [`791f4000`](https://github.com/PrismJS/prism/commit/791f4000)

### Updated plugins

* __File Highlight__
    * Simplify lang regex on File Highlight plugin (#1399) [`7bc9a4a1`](https://github.com/PrismJS/prism/commit/7bc9a4a1)
    * File Highlight: Fix issue causing the Download button to show up on every code blocks. [`cd22499c`](https://github.com/PrismJS/prism/commit/cd22499c)
* __Show Language__
    * Move guard into conditional and check for language [`eef860cb`](https://github.com/PrismJS/prism/commit/eef860cb)
    * Don't process language if block language not set [`c1118692`](https://github.com/PrismJS/prism/commit/c1118692)

### Updated themes

* Add .token.class-name to rest of themes (#1360) [`f356dfe7`](https://github.com/PrismJS/prism/commit/f356dfe7)
* __Coy__
    * Add double-class specificity hack (#1435) [`b848e9d6`](https://github.com/PrismJS/prism/commit/b848e9d6)

### Other

* Add Chinese translation [`f2b19644`](https://github.com/PrismJS/prism/commit/f2b19644)
* Add missing CHANGELOG links [`829e5cd9`](https://github.com/PrismJS/prism/commit/829e5cd9)
* __Infrastructure__
    * Create CNAME [`0e6fbada`](https://github.com/PrismJS/prism/commit/0e6fbada)
    * Delete CNAME [`2f5f9c3c`](https://github.com/PrismJS/prism/commit/2f5f9c3c)
* __Website__
    * Moved tutorial link to the end of the list [`854cc5b3`](https://github.com/PrismJS/prism/commit/854cc5b3)
    * Fix mixed content warning [`90aaee10`](https://github.com/PrismJS/prism/commit/90aaee10)
    * Update documentation for node & webpack usage [`1e99e961`](https://github.com/PrismJS/prism/commit/1e99e961)
    * Use rel="icon" instead of rel="shortcut icon" (#1398) [`d95f8fb4`](https://github.com/PrismJS/prism/commit/d95f8fb4)
    * Added Angular tutorial link [`c436a7c7`](https://github.com/PrismJS/prism/commit/c436a7c7)
```

</details>

<details>
<summary><code>v1.15.0..v1.16.0</code></summary>

```markdown
Rebuild found: Rebuilt Prism (#1794)
Rebuild found: Deleted prism-hdl.min.js (#1712)

### TODO:

* Travis: Fail when changed files are detected (#1819) [`66b44e3b`](https://github.com/PrismJS/prism/commit/66b44e3b)
* Tests: Additional checks for Prism functions (#1803) [`c3e74ea3`](https://github.com/PrismJS/prism/commit/c3e74ea3)
* Added alias tests (#1832) [`5c1a6fb2`](https://github.com/PrismJS/prism/commit/5c1a6fb2)
* Autoloader: Added support for aliases (#1829) [`52889b5b`](https://github.com/PrismJS/prism/commit/52889b5b)
* Added missing aliases (#1830) [`8d28c74c`](https://github.com/PrismJS/prism/commit/8d28c74c)
* npm: Fixed `test` script (#1809) [`bc649dfa`](https://github.com/PrismJS/prism/commit/bc649dfa)
* Applied Array.isArray (#1804) [`11d0f75e`](https://github.com/PrismJS/prism/commit/11d0f75e)
* Add unit tests to the Keep Markup plugin (#1646) [`a944c418`](https://github.com/PrismJS/prism/commit/a944c418)
* Added scripts directory (#1781) [`439ea1ee`](https://github.com/PrismJS/prism/commit/439ea1ee)
* More variables for better code compression (#1489) [`bc53e093`](https://github.com/PrismJS/prism/commit/bc53e093)
* Refactored tests (#1795) [`832a9643`](https://github.com/PrismJS/prism/commit/832a9643)
* Tests: Pretty-printed token stream (#1801) [`9ea6d600`](https://github.com/PrismJS/prism/commit/9ea6d600)
* Fixed patterns which can match the empty string (#1775) [`86dd3e42`](https://github.com/PrismJS/prism/commit/86dd3e42)
* Fixed dependencies of Pug and Pure (#1759) [`c9a32674`](https://github.com/PrismJS/prism/commit/c9a32674)
* Ruby/ERB: Fixed block comments (#1768) [`c805f859`](https://github.com/PrismJS/prism/commit/c805f859)
* Markup: Added support for CSS and JS inside of CDATAs (#1660) [`57127701`](https://github.com/PrismJS/prism/commit/57127701)
* Added T4 Text Templates (#1699) [`16f2ad06`](https://github.com/PrismJS/prism/commit/16f2ad06)
* Added doc comment highlighting (#1541) [`493d19ef`](https://github.com/PrismJS/prism/commit/493d19ef)
* Fix JSONP support (#1745) [`b5041cf9`](https://github.com/PrismJS/prism/commit/b5041cf9)
* Inline regex source with gulp (#1537) [`e894fc89`](https://github.com/PrismJS/prism/commit/e894fc89)
* Show Language plugin alias support and improvements (#1683) [`4c66d72c`](https://github.com/PrismJS/prism/commit/4c66d72c)
* Fix downloads page fetching from GitHub(#1684) [`dbd3555e`](https://github.com/PrismJS/prism/commit/dbd3555e)
* Improve C language (#1697) [`7eccea5c`](https://github.com/PrismJS/prism/commit/7eccea5c)
* Identify JavaScript function parameters (#1446) [`0cc8c56a`](https://github.com/PrismJS/prism/commit/0cc8c56a)
* Add file extensions support for major languages (#1478) [`0c8f6504`](https://github.com/PrismJS/prism/commit/0c8f6504)
* Ignore duplicates in insertBefore (#1628) [`d33d259c`](https://github.com/PrismJS/prism/commit/d33d259c)
* CSS: Comma punctuation (#1632) [`1b812386`](https://github.com/PrismJS/prism/commit/1b812386)
* Resolved merge conflict [`c988936b`](https://github.com/PrismJS/prism/commit/c988936b)
* Merge remote-tracking branch 'upstream/master' [`59f841e5`](https://github.com/PrismJS/prism/commit/59f841e5)
* Corrected load order of Show Invisibles (#1612) [`6e0c6e86`](https://github.com/PrismJS/prism/commit/6e0c6e86)
* Merge remote-tracking branch 'upstream/master' [`5ded688a`](https://github.com/PrismJS/prism/commit/5ded688a)
* Display language aliases (#1626) [`654b527b`](https://github.com/PrismJS/prism/commit/654b527b)
* Merge remote-tracking branch 'upstream/master' [`21033636`](https://github.com/PrismJS/prism/commit/21033636)
* Merge remote-tracking branch 'upstream/master' [`24ad1df4`](https://github.com/PrismJS/prism/commit/24ad1df4)
* Remove batch's shell alias (#1543) [`7155e60f`](https://github.com/PrismJS/prism/commit/7155e60f)
* Added the comma to the list of CSS punctuation [`7ea2ff28`](https://github.com/PrismJS/prism/commit/7ea2ff28)
* Updated styles of show invisibles (#1607) [`2ba62268`](https://github.com/PrismJS/prism/commit/2ba62268)
* C/C++/Java operator update (#1528) [`7af8f8be`](https://github.com/PrismJS/prism/commit/7af8f8be)
* Added missing aliases to components.json (#1503) [`2fb66e04`](https://github.com/PrismJS/prism/commit/2fb66e04)
* Replaced all occurrences of `new RegExp` with `RegExp` (#1493) [`44fed4d3`](https://github.com/PrismJS/prism/commit/44fed4d3)
* `insertBefore` now correctly updates references (#1531) [`9dfec340`](https://github.com/PrismJS/prism/commit/9dfec340)
* Fixed peer dependencies in download page (#1491) [`9d15ff6e`](https://github.com/PrismJS/prism/commit/9d15ff6e)
* Improve download page typography (#1484) [`b1c2f4df`](https://github.com/PrismJS/prism/commit/b1c2f4df)

### New components

* __Augmented Backus–Naur form__: Added ANBF language (#1753) [`6d98f0e7`](https://github.com/PrismJS/prism/commit/6d98f0e7)
* __Backus–Naur form__ & __Routing Backus–Naur form__: Added BNF and RBNF languages (#1754) [`1df96c55`](https://github.com/PrismJS/prism/commit/1df96c55)
* __CIL__: Add new language: CIL (#1593) [`38def334`](https://github.com/PrismJS/prism/commit/38def334)
* __CMake__: Added support for CMake language (#1820) [`30779976`](https://github.com/PrismJS/prism/commit/30779976)
* __EJS__: Added EJS (#1769) [`c37c90df`](https://github.com/PrismJS/prism/commit/c37c90df)
* __Extended Backus–Naur form__: Added EBNF language (#1756) [`13e1c97d`](https://github.com/PrismJS/prism/commit/13e1c97d)
* __G-code__: Add G-code language (#1572) [`2288c25e`](https://github.com/PrismJS/prism/commit/2288c25e)
* __GameMaker Language__: Add GameMaker Language support (#1551) [`e529edd8`](https://github.com/PrismJS/prism/commit/e529edd8)
* __HCL__: Added support for HCL (#1594) [`c939df8e`](https://github.com/PrismJS/prism/commit/c939df8e)
* __Java stack trace__: Add support for Java stack traces (#1520) [`4a8219a4`](https://github.com/PrismJS/prism/commit/4a8219a4)
* __JS Extras__: Added JS Extras (#1743) [`bb628606`](https://github.com/PrismJS/prism/commit/bb628606)
* __JSON5__: Added JSON5 language (#1744) [`64dc049d`](https://github.com/PrismJS/prism/commit/64dc049d)
* __N1QL__: Added N1QL language support (#1620) [`7def8f5c`](https://github.com/PrismJS/prism/commit/7def8f5c)
* __Nand To Tetris HDL__: Added the Nand2Tetris HDL language (#1710) [`b94b56c1`](https://github.com/PrismJS/prism/commit/b94b56c1)
* __Regex__: Regex language (#1682) [`571704cb`](https://github.com/PrismJS/prism/commit/571704cb)
* __TOML__: Add TOML support (#1488) [`5b6ad70d`](https://github.com/PrismJS/prism/commit/5b6ad70d)
* __Vala__: Added Vala language (#1658) [`b48c012c`](https://github.com/PrismJS/prism/commit/b48c012c)

### Updated components

* __Apache Configuration__
    * Apache config: Minor improvements + new keyword (#1823) [`a91be7b2`](https://github.com/PrismJS/prism/commit/a91be7b2)
* __AsciiDoc__
    * Added `adoc` alias for AsciiDoc (#1685) [`88434f7a`](https://github.com/PrismJS/prism/commit/88434f7a)
* __Bash__
    * Added `pnpm` function to Bash (#1734) [`fccfb98d`](https://github.com/PrismJS/prism/commit/fccfb98d)
    * Added `yarn add` to bash functions (#1731) [`3a32cb75`](https://github.com/PrismJS/prism/commit/3a32cb75)
    * Add additional commands to bash (#1577) [`a2230c38`](https://github.com/PrismJS/prism/commit/a2230c38)
* __C-like__
    * Simplify function pattern of C-like language (#1552) [`b520e1b6`](https://github.com/PrismJS/prism/commit/b520e1b6)
* __C#__
    * Improvements to C# operator and punctuation (#1532) [`3b1e0916`](https://github.com/PrismJS/prism/commit/3b1e0916)
* __CSS__
    * CSS: Selectors can contain any string (#1638) [`a2d445d0`](https://github.com/PrismJS/prism/commit/a2d445d0)
    * Allow multiline CSS at-rules (#1676) [`4f6f3c7d`](https://github.com/PrismJS/prism/commit/4f6f3c7d)
    * Fix tokenizing !important (#1585) [`c1d6cb85`](https://github.com/PrismJS/prism/commit/c1d6cb85)
* __CSS Extras__
    * CSS extras: Highlighting for pseudo class arguments (#1650) [`70a40414`](https://github.com/PrismJS/prism/commit/70a40414)
    * CSS: Highlight attribute selector (#1671) [`245b59d4`](https://github.com/PrismJS/prism/commit/245b59d4)
    * Fixed CSS extra variable (#1649) [`9de47d3a`](https://github.com/PrismJS/prism/commit/9de47d3a)
    * Identify CSS units and variables (#1450) [`5fcee966`](https://github.com/PrismJS/prism/commit/5fcee966)
    * Reuse CSS selector pattern in CSS Extras (#1637) [`e2f2fd19`](https://github.com/PrismJS/prism/commit/e2f2fd19)
* __Django/Jinja2__
    * Django/Jinja2 improvements (#1800) [`f2467488`](https://github.com/PrismJS/prism/commit/f2467488)
* __F#__
    * Improve F# (#1573) [`00bfc969`](https://github.com/PrismJS/prism/commit/00bfc969)
    * F#: Chars can only contain one character (#1570) [`f96b083a`](https://github.com/PrismJS/prism/commit/f96b083a)
* __GraphQL__
    * Added GraphQL improvements and tests (#1788) [`b2298b12`](https://github.com/PrismJS/prism/commit/b2298b12)
    * Improved field highlighting for GraphQL (#1711) [`44aeffb9`](https://github.com/PrismJS/prism/commit/44aeffb9)
* __Haskell__
    * Added `hs` alias for Haskell (#1831) [`64baec3c`](https://github.com/PrismJS/prism/commit/64baec3c)
* __HTTP__
    * Improved HTTP content highlighting (#1598) [`1b75da90`](https://github.com/PrismJS/prism/commit/1b75da90)
* __Ini__
    * Add support for # comments to INI language (#1730) [`baf6bb0c`](https://github.com/PrismJS/prism/commit/baf6bb0c)
* __Java__
    * Added module keywords to Java. (#1655) [`6e250a5f`](https://github.com/PrismJS/prism/commit/6e250a5f)
    * Improve Java (#1474) [`81bd8f0b`](https://github.com/PrismJS/prism/commit/81bd8f0b)
    * Add Java 10 support (#1549) [`8c981a22`](https://github.com/PrismJS/prism/commit/8c981a22)
* __JavaScript__
    * JS: Keyword fix (#1808) [`f2d8e1c7`](https://github.com/PrismJS/prism/commit/f2d8e1c7)
    * JS: Fixed variables named "async" (#1738) [`3560c643`](https://github.com/PrismJS/prism/commit/3560c643)
    * Improved JS constant pattern (#1737) [`7bcec584`](https://github.com/PrismJS/prism/commit/7bcec584)
    * Improved JS function pattern (#1736) [`8378ac83`](https://github.com/PrismJS/prism/commit/8378ac83)
    * Fix `function-variable` in JS (#1739) [`bfbea4d6`](https://github.com/PrismJS/prism/commit/bfbea4d6)
    * Make `undefined` a keyword in JS (#1740) [`d9fa29a8`](https://github.com/PrismJS/prism/commit/d9fa29a8)
    * Improved JavaScript parameter recognization (#1722) [`57a92035`](https://github.com/PrismJS/prism/commit/57a92035)
    * Improve regex detection in JS (#1473) [`2a4758ab`](https://github.com/PrismJS/prism/commit/2a4758ab)
    * Fixed lowercase supposed class names (#1544) [`a47c05ad`](https://github.com/PrismJS/prism/commit/a47c05ad)
    * Added support for JS BigInt literals (#1542) [`2b62e57b`](https://github.com/PrismJS/prism/commit/2b62e57b)
    * Highlighting of supposed classes and functions (#1482) [`c40f6047`](https://github.com/PrismJS/prism/commit/c40f6047)
    * Fix regex for `catch` and `finally` (#1527) [`ebd1b9a6`](https://github.com/PrismJS/prism/commit/ebd1b9a6)
* __JSON__
    * Added `keyword` alias to JSON's `null` (#1733) [`eee06649`](https://github.com/PrismJS/prism/commit/eee06649)
    * Cleaned up JSON (#1596) [`da474c77`](https://github.com/PrismJS/prism/commit/da474c77)
    * Adds support for comments in JSON (#1595) [`8720b3e6`](https://github.com/PrismJS/prism/commit/8720b3e6)
    * Fix bugs in JSON language [`74fe81c6`](https://github.com/PrismJS/prism/commit/74fe81c6)
* __Less__
    * Remove useless insertBefore in LESS (#1629) [`86d31793`](https://github.com/PrismJS/prism/commit/86d31793)
* __Lisp__
    * Fix Lisp exponential string pattern (#1763) [`5bd182c0`](https://github.com/PrismJS/prism/commit/5bd182c0)
* __Markdown__
    * Markdown: The 'md' alias is now recognized by hooks (#1771) [`8ca3d65b`](https://github.com/PrismJS/prism/commit/8ca3d65b)
    * Add support for code blocks in Markdown (#1562) [`b0717e70`](https://github.com/PrismJS/prism/commit/b0717e70)
    * Fixed Markdown headers (#1557) [`c6584290`](https://github.com/PrismJS/prism/commit/c6584290)
    * Added strike support to markdown (#1563) [`9d2fddc2`](https://github.com/PrismJS/prism/commit/9d2fddc2)
* __Markup__
    * Markup `addInline` improvements (#1798) [`af67c32e`](https://github.com/PrismJS/prism/commit/af67c32e)
    * Fix for markup attributes (#1752) [`c3862a24`](https://github.com/PrismJS/prism/commit/c3862a24)
    * Decouple XML from Markup (#1603) [`0030a4ef`](https://github.com/PrismJS/prism/commit/0030a4ef)
* __Markup templating__
    * Markup-templating improvements (#1653) [`b62e282b`](https://github.com/PrismJS/prism/commit/b62e282b)
* __nginx__
    * Add new keywords to nginx (#1587) [`0d73f7f5`](https://github.com/PrismJS/prism/commit/0d73f7f5)
* __PHP__
    * PHP: Fixed closing tag issue (#1652) [`289ddd9b`](https://github.com/PrismJS/prism/commit/289ddd9b)
    * Made false, true, and null constants in PHP (#1694) [`439e3bd7`](https://github.com/PrismJS/prism/commit/439e3bd7)
    * Update PHP keywords (#1690) [`55fb0f8e`](https://github.com/PrismJS/prism/commit/55fb0f8e)
    * Improve recognition of constants in PHP (#1688) [`f1026b4b`](https://github.com/PrismJS/prism/commit/f1026b4b)
* __Python__
    * Improvements to Python F-strings and string prefixes (#1642) [`a69c2b62`](https://github.com/PrismJS/prism/commit/a69c2b62)
    * Add decorator support to Python (#1639) [`2577b6e6`](https://github.com/PrismJS/prism/commit/2577b6e6)
    * Python: Operator keywords are now keywords (#1617) [`1d1fb800`](https://github.com/PrismJS/prism/commit/1d1fb800)
* __React JSX__
    * Support JSX/TSX class-name with dot (#1725) [`4362e42c`](https://github.com/PrismJS/prism/commit/4362e42c)
    * React component tags are styled as classes in JSX (#1519) [`3e1a9a3d`](https://github.com/PrismJS/prism/commit/3e1a9a3d)
* __Reason__
    * Added additional operators to Reason (#1648) [`8b1bb469`](https://github.com/PrismJS/prism/commit/8b1bb469)
* __Ruby__
    * Consistent Ruby method highlighting (#1523) [`72775919`](https://github.com/PrismJS/prism/commit/72775919)
* __Rust__
    * Add missing keywords to rust. (#1634) [`3590edde`](https://github.com/PrismJS/prism/commit/3590edde)
* __SAS__
    * Added new SAS keywords (#1784) [`3b396ef5`](https://github.com/PrismJS/prism/commit/3b396ef5)
* __Sass (Scss)__
    * Add `keyword` alias for SCSS' `null` (#1735) [`bd0378f0`](https://github.com/PrismJS/prism/commit/bd0378f0)
    * Move SCSS `property` definition (#1633) [`0536fb14`](https://github.com/PrismJS/prism/commit/0536fb14)
    * Fixed that selector pattern can take exponential time (#1499) [`0f75d9d4`](https://github.com/PrismJS/prism/commit/0f75d9d4)
* __Scheme__
    * Scheme: Minor improvements (#1814) [`191830f2`](https://github.com/PrismJS/prism/commit/191830f2)
    * Fixed operator-like functions in Scheme (#1467) [`f8c8add2`](https://github.com/PrismJS/prism/commit/f8c8add2)
    * Scheme improvements (#1556) [`225dd3f7`](https://github.com/PrismJS/prism/commit/225dd3f7)
    * fix function without arguments in scheme language (#1463) [`12a827e7`](https://github.com/PrismJS/prism/commit/12a827e7)
* __Smalltalk__
    * Smalltalk: Allowed empty strings and comments (#1747) [`5fd7577a`](https://github.com/PrismJS/prism/commit/5fd7577a)
* __Smarty__
    * Removed useless `insertBefore` call in Smarty (#1677) [`bc49c361`](https://github.com/PrismJS/prism/commit/bc49c361)
* __SQL__
    * SQL Quoted variables are now greedy (#1510) [`42d119a2`](https://github.com/PrismJS/prism/commit/42d119a2)
    * Added support for quote escapes to SQL strings (#1500) [`a59a7926`](https://github.com/PrismJS/prism/commit/a59a7926)
* __TypeScript__
    * Enhance definitions in TypeScript component (#1522) [`11695629`](https://github.com/PrismJS/prism/commit/11695629)
* __YAML__
    * Allow YAML strings to have trailing comments (#1602) [`1c5f28a9`](https://github.com/PrismJS/prism/commit/1c5f28a9)

### Updated plugins

* Better class name detection for plugins (#1772) [`c9762c6f`](https://github.com/PrismJS/prism/commit/c9762c6f)
* __Autolinker__
    * Fix Autolinker url-decoding all tokens (#1723) [`8cf20d49`](https://github.com/PrismJS/prism/commit/8cf20d49)
* __Autoloader__
    * Resolved variable name clash (#1568) [`bfa5a8d9`](https://github.com/PrismJS/prism/commit/bfa5a8d9)
* __Command Line__
    * Fixed class regex for Command Line plugin (#1566) [`9f6e5026`](https://github.com/PrismJS/prism/commit/9f6e5026)
* __File Highlight__
    * Fix typo (#1755) [`ce9616a0`](https://github.com/PrismJS/prism/commit/ce9616a0)
    * Prevent double-loading & add scope to File Highlight (#1586) [`10239c14`](https://github.com/PrismJS/prism/commit/10239c14)
* __JSONP Highlight__
    * JSONP highlight: Fixed minified adapter names (#1793) [`5dd8f916`](https://github.com/PrismJS/prism/commit/5dd8f916)
    * Cleanup JSONP highlight code (#1674) [`28489698`](https://github.com/PrismJS/prism/commit/28489698)
* __Line Numbers__
    * Line numbers: Added inheritance for the `line-numbers` class (#1799) [`14be7489`](https://github.com/PrismJS/prism/commit/14be7489)
* __Previewers__
    * Fixed Previewers bug #1496 (#1497) [`4b56f3c1`](https://github.com/PrismJS/prism/commit/4b56f3c1)
* __Show Invisibles__
    * Show invisibles inside tokens (#1610) [`1090b253`](https://github.com/PrismJS/prism/commit/1090b253)
    * Revert "Show invisibles inside tokens" [`7a2d153b`](https://github.com/PrismJS/prism/commit/7a2d153b)
    * Show invisibles inside tokens [`2d622f17`](https://github.com/PrismJS/prism/commit/2d622f17)
* __Toolbar__
    * Toolbar: Minor improvements (#1818) [`3ad47047`](https://github.com/PrismJS/prism/commit/3ad47047)

### Updated themes

* Themes: Normalized the font-size of pre and code (#1791) [`878ef295`](https://github.com/PrismJS/prism/commit/878ef295)
* __Coy__
    * Correct typo (#1508) [`c322fc80`](https://github.com/PrismJS/prism/commit/c322fc80)

### Other

* CHANGELOG for v1.16.0 [`695dddce`](https://github.com/PrismJS/prism/commit/695dddce)
* Added issue templates (#1805) [`dedb475f`](https://github.com/PrismJS/prism/commit/dedb475f)
* Fixed CHANGELOG.md formatting (#1707) [`b1f8a65d`](https://github.com/PrismJS/prism/commit/b1f8a65d)
* Fixed CHANGELOG.md (#1704) [`66d2104a`](https://github.com/PrismJS/prism/commit/66d2104a)
* Mention Prism Themes in README (#1625) [`5db04656`](https://github.com/PrismJS/prism/commit/5db04656)
* Update README.md (#1553) [`6d1a2c61`](https://github.com/PrismJS/prism/commit/6d1a2c61)
* Add travis repo badge to readme (#1561) [`716923f4`](https://github.com/PrismJS/prism/commit/716923f4)
* Linkify changelog more + add missing PR references [`2a100db7`](https://github.com/PrismJS/prism/commit/2a100db7)
* Linkify CHANGELOG [`fedf03f6`](https://github.com/PrismJS/prism/commit/fedf03f6)
* __Core__
    * Made prism-core a little more editor friendly (#1776) [`bac09f0a`](https://github.com/PrismJS/prism/commit/bac09f0a)
    * Core: Avoid redeclaring variables in util.clone (#1778) [`b06f532f`](https://github.com/PrismJS/prism/commit/b06f532f)
    * Improved languages.DFS and util.clone (#1506) [`152a68ef`](https://github.com/PrismJS/prism/commit/152a68ef)
    * Call `insert-before` hook properly (#1709) [`393ab164`](https://github.com/PrismJS/prism/commit/393ab164)
    * Remove the Prism.tokenize language parameter (#1654) [`fbf0b094`](https://github.com/PrismJS/prism/commit/fbf0b094)
    * Remove unused `insertBefore` overload (#1631) [`39686e12`](https://github.com/PrismJS/prism/commit/39686e12)
    * Improve `Prism.util.type` performance (#1545) [`2864fe24`](https://github.com/PrismJS/prism/commit/2864fe24)
    * Invoke `callback` after `after-highlight` hook (#1588) [`bfbe4464`](https://github.com/PrismJS/prism/commit/bfbe4464)
* __Infrastructure__
    * Split gulpfile.js [`9cf9b75e`](https://github.com/PrismJS/prism/commit/9cf9b75e)
    * 1.16.0 [`886698d5`](https://github.com/PrismJS/prism/commit/886698d5)
    * Add command to generate CHANGELOG [`3abaf68d`](https://github.com/PrismJS/prism/commit/3abaf68d)
    * Adjusted .npmignore (#1834) [`29a30c62`](https://github.com/PrismJS/prism/commit/29a30c62)
    * Name in composer.json set to lowercase (#1824) [`4f78f1d6`](https://github.com/PrismJS/prism/commit/4f78f1d6)
    * npm: Updated all dependencies (#1742) [`9d908d5a`](https://github.com/PrismJS/prism/commit/9d908d5a)
    * gulp: Refactoring (#1780) [`6c9fe257`](https://github.com/PrismJS/prism/commit/6c9fe257)
    * Update gulp to version 4.0.0 (#1779) [`06627f6a`](https://github.com/PrismJS/prism/commit/06627f6a)
    * Improve gulp error messages with pump (#1741) [`671f4ca0`](https://github.com/PrismJS/prism/commit/671f4ca0)
    * Inline ALL regexes (#1716) [`217a6ea4`](https://github.com/PrismJS/prism/commit/217a6ea4)
    * Change tested NodeJS versions (#1651) [`6ec71e0b`](https://github.com/PrismJS/prism/commit/6ec71e0b)
    * Set default indentation size (#1516) [`e63d1597`](https://github.com/PrismJS/prism/commit/e63d1597)
* __Website__
    * Autoloader: Fixed the directory of scripts (#1828) [`fd4c764f`](https://github.com/PrismJS/prism/commit/fd4c764f)
    * Fixed download page (#1811) [`77c57446`](https://github.com/PrismJS/prism/commit/77c57446)
    * More persistent test page (#1529) [`3100fa31`](https://github.com/PrismJS/prism/commit/3100fa31)
    * Docs: Added missing parameter (#1774) [`18f2921d`](https://github.com/PrismJS/prism/commit/18f2921d)
    * Test page: Show tokens option (#1757) [`729cb28b`](https://github.com/PrismJS/prism/commit/729cb28b)
    * Some encouragement for visitors of PrismJS.com to request new languages (#1760) [`ea769e0b`](https://github.com/PrismJS/prism/commit/ea769e0b)
    * Fixed JSON/JSONP examples (#1765) [`ae4842db`](https://github.com/PrismJS/prism/commit/ae4842db)
    * Fixed Toolbar plugin example (#1726) [`5311ca32`](https://github.com/PrismJS/prism/commit/5311ca32)
    * Line Numbers plugin instructions clarifications (#1719) [`00f4f04f`](https://github.com/PrismJS/prism/commit/00f4f04f)
    * Remove parentheses from download page (#1627) [`2ce0666d`](https://github.com/PrismJS/prism/commit/2ce0666d)
    * Fix typos & other issues in JSONP docs (#1672) [`cd058a91`](https://github.com/PrismJS/prism/commit/cd058a91)
    * Remove dead tutorial (#1702) [`e2d3bc7e`](https://github.com/PrismJS/prism/commit/e2d3bc7e)
    * Added new third-party tutorial for using Prism in Gutenberg (#1701) [`ff9ccbe5`](https://github.com/PrismJS/prism/commit/ff9ccbe5)
    * Updated website table of contents styles (#1681) [`efdd96c3`](https://github.com/PrismJS/prism/commit/efdd96c3)
    * Clean up Previewers' page (#1630) [`b0d1823c`](https://github.com/PrismJS/prism/commit/b0d1823c)
    * Fixes regex for JS examples (#1591) [`b41fb8f1`](https://github.com/PrismJS/prism/commit/b41fb8f1)
    * Fixed empty link in extending (#1507) [`74916d48`](https://github.com/PrismJS/prism/commit/74916d48)
    * Updated index.html to fix broken instructions (#1462) [`7418dfdd`](https://github.com/PrismJS/prism/commit/7418dfdd)
    * Remove extraneous class [`e00b408f`](https://github.com/PrismJS/prism/commit/e00b408f)
    * Add Python triple-quoted strings "known failure" (#1449) [`334c7bca`](https://github.com/PrismJS/prism/commit/334c7bca)
```

</details>

<details>
<summary><code>v1.16.0..HEAD</code></summary>

```markdown

### TODO:

* Merge branch 'master' into gulpfilejs-dir [`15001d69`](https://github.com/PrismJS/prism/commit/15001d69)
* Tests: Added test for empty regexes (#1847) [`c1e6a7fd`](https://github.com/PrismJS/prism/commit/c1e6a7fd)

### New components


### Updated components

* __CSS__
    * Extended `url` inside (#1874) [`f0a10669`](https://github.com/PrismJS/prism/commit/f0a10669)
    * Removed useless flag and modifier (#1875) [`74050c68`](https://github.com/PrismJS/prism/commit/74050c68)
* __CSS Extras__
    * Added `even` & `odd` keywords to `n-th` pattern (#1872) [`5e5a3e00`](https://github.com/PrismJS/prism/commit/5e5a3e00)
* __JavaScript__
    * JS: Template strings: Increased bracket count of interpolations (#1845) [`c13d6e7d`](https://github.com/PrismJS/prism/commit/c13d6e7d)
    * Added support for `s` regex flag (#1846) [`9e164935`](https://github.com/PrismJS/prism/commit/9e164935)
    * Added missing semicolon (#1856) [`e2683959`](https://github.com/PrismJS/prism/commit/e2683959)
* __JSON__
    * Kinda fixed comment issue (#1853) [`cbe05ec3`](https://github.com/PrismJS/prism/commit/cbe05ec3)
* __Rust__
    * Add async / await keywords for Rust. (#1882) [`4faa3314`](https://github.com/PrismJS/prism/commit/4faa3314)
    * Improved punctuation and operators (#1839) [`a42b1557`](https://github.com/PrismJS/prism/commit/a42b1557)

### Updated plugins

* __Autolinker__
    * Improved URL regex (#1842) [`eb28b62b`](https://github.com/PrismJS/prism/commit/eb28b62b)
* __Command Line__
    * Fix for uncaught errors for empty 'commandLine' object. (#1862) [`c24831b5`](https://github.com/PrismJS/prism/commit/c24831b5)
* __Custom Class__
    * Added mapper functions for language specific transformations (#1873) [`acceb3b5`](https://github.com/PrismJS/prism/commit/acceb3b5)
* __Line Highlight__
    * Batching DOM read/writes to avoid reflows (#1865) [`632ce00c`](https://github.com/PrismJS/prism/commit/632ce00c)

### Updated themes


### Other

* Readme: Minor changes (#1857) [`77e403cb`](https://github.com/PrismJS/prism/commit/77e403cb)
* Clearer description for the highlighting bug report template (#1850) [`2f9c9261`](https://github.com/PrismJS/prism/commit/2f9c9261)
* __Core__
    * Made `language-none` the default language (#1858) [`fd691c52`](https://github.com/PrismJS/prism/commit/fd691c52)
    * Removed `parent` from the `wrap` hook's environment (#1837) [`65a4e894`](https://github.com/PrismJS/prism/commit/65a4e894)
* __Infrastructure__
    * Refactoring, more doc, and minor changes [`25404faa`](https://github.com/PrismJS/prism/commit/25404faa)
    * Sorted new components [`fff93e07`](https://github.com/PrismJS/prism/commit/fff93e07)
    * Split gulpfile.js [`9cf9b75e`](https://github.com/PrismJS/prism/commit/9cf9b75e)
* __Website__
    * JSONP Highlight: Fixed examples (#1877) [`f8ae465d`](https://github.com/PrismJS/prism/commit/f8ae465d)
    * Copy to clipboard: Fixed typo (#1869) [`59d4323f`](https://github.com/PrismJS/prism/commit/59d4323f)
    * New tutorial for Drupal (#1859) [`d2089d83`](https://github.com/PrismJS/prism/commit/d2089d83)
    * Line numbers: Fixed typo on webpage (#1838) [`0f16eb87`](https://github.com/PrismJS/prism/commit/0f16eb87)

```

</details>

### CODE REVIEW

File: gulpfile.js/index.js [hunk 1]
```diff
@@ -7,26 +9,11 @@ const concat = require('gulp-concat');
...
-		'plugins/file-highlight/prism-file-highlight.js'
-	],
-	plugins: ['plugins/**/*.js', '!plugins/**/*.min.js'],
-	showLanguagePlugin: 'plugins/show-language/prism-show-language.js',
-	autoloaderPlugin: 'plugins/autoloader/prism-autoloader.js',
-	changelog: 'CHANGELOG.md'
-};
+const paths = require('./paths');
+const { premerge } = require('./premerge');
+const { changes, linkify } = require('./changelog');
```
Comment (RunDevelopment) [inline gulpfile.js/index.js]: Maybe we should use `Object.assign(export, require('./premerge'), require('./changelog'));` here?

Comment (ExE-Boss) [reply gulpfile.js/index.js]: If anything, it should be:
```suggestion
Object.assign(exports, require('./premerge'), require('./changelog'));
```

`export` is a keyword, `exports` is the CommonJS variable.

File: gulpfile.js/premerge.js [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+
+	return git.status().then(res => {
+		if (res.files.length > 0) {
+			console.log(res);
+			throw new Error('There are changes in the file system. Did you forget to run gulp?');
+		}
+	});
+}
+
+exports.premerge = gitChanges;
```
Comment (ExE-Boss) [inline gulpfile.js/premerge.js]:
```suggestion
module.exports = gitChanges;
```

File: gulpfile.js/index.js [hunk 3]
```diff
@@ -7,26 +9,11 @@ const concat = require('gulp-concat');
...
-		'components/prism-javascript.js',
-		'plugins/file-highlight/prism-file-highlight.js'
-	],
-	plugins: ['plugins/**/*.js', '!plugins/**/*.min.js'],
-	showLanguagePlugin: 'plugins/show-language/prism-show-language.js',
-	autoloaderPlugin: 'plugins/autoloader/prism-autoloader.js',
-	changelog: 'CHANGELOG.md'
-};
+const paths = require('./paths');
+const { premerge } = require('./premerge');
```
Comment (ExE-Boss) [inline gulpfile.js/index.js]:
```suggestion
const premerge = require('./premerge');
```

File: gulpfile.js/premerge.js (hunk 2 above)
Comment (RunDevelopment) [reply gulpfile.js/premerge.js]: I didn't want to do this because it cuts off the path for additional exports later on.

It doesn't really matter right now but all other modules also export an object, so I wanted to keep it consistent.

File: gulpfile.js/index.js (hunk 1 above)
Comment (RunDevelopment) [reply gulpfile.js/index.js]: Ahhh right. Small typo.

File: gulpfile.js/changelog.js [hunk 4]
```diff
@@ -0,0 +1,380 @@
...
+	const a = [];
+
+	a['sort'] = function () {
+		return Array.prototype.sort.call(this, compareFn);
+	};
+	a[Symbol.iterator] = function* () {
+		const copy = [];
+		for (let i = 0; i < this.length; i++) {
+			copy.push(this[i]);
+		}
```
Comment (mAAdhaTTah) [inline gulpfile.js/changelog.js]: `this.slice()` is less code.

File: gulpfile.js/changelog.js [hunk 5]
```diff
@@ -0,0 +1,380 @@
...
+		const commits = !res ? [] : res.trim().split(/\n/g);
+
+		return Promise.all(commits.map(getCommitInfo));
+	});
+}
+
+const revisionRanges = {
+	nextRelease: git.raw(['describe', '--abbrev=0', '--tags']).then(res => `${res.trim()}..HEAD`),
+	v1_15_0__HEAD: 'v1.15.0..HEAD',
+	v1_14_0__v1_15_0: 'v1.14.0..v1.15.0',
```
Comment (mAAdhaTTah) [inline gulpfile.js/changelog.js]: Does this need to change every release? What's the story here?

File: gulpfile.js/changelog.js [hunk 6]
```diff
@@ -0,0 +1,380 @@
...
+		}
+
+
+		/** @param {CommitChange} change */
+		function notGenerated(change) {
+			return !change.file.endsWith('.min.js') && ['prism.js', 'components.js', 'package-lock.json'].indexOf(change.file) === -1;
+		}
+		/** @param {CommitChange} change */
+		function notPartlyGenerated(change) {
+			return change.file !== 'plugins/autoloader/prism-autoloader.js' &&
```
Comment (mAAdhaTTah) [inline gulpfile.js/changelog.js]: Will this also remove these files from manual changes to them?

File: gulpfile.js/changelog.js [hunk 7]
```diff
@@ -0,0 +1,380 @@
...
+				// `components.json` has to be modified
+				if (relevantChanges.some(c => c.file === 'components.json')) {
+					relevantChanges = relevantChanges.filter(and(notComponentsJSON, notPartlyGenerated));
+
+					// now, only the newly added JS should be left
+					if (relevantChanges.length === 1) {
+						const change = relevantChanges[0];
+						if (change.mode === 'A' && change.file.startsWith('components/prism-')) {
+							var lang = change.file.match(/prism-([\w-]+)\.js$/)[1];
+							var titles = [languages[lang].title];
```
Comment (mAAdhaTTah) [inline gulpfile.js/changelog.js]: If we're gonna es6 the gulpfile, use `let` or `const` all the way down.

File: gulpfile.js/index.js (hunk 1 above)
Comment (mAAdhaTTah) [reply gulpfile.js/index.js]: Eh, I do like having all the commands listed at the bottom of the file together.

File: gulpfile.js/changelog.js (hunk 7 above)
Comment (RunDevelopment) [reply gulpfile.js/changelog.js]: Force of habit.

File: gulpfile.js/changelog.js (hunk 5 above)
Comment (RunDevelopment) [reply gulpfile.js/changelog.js]: Just some constants I used during development.
I'll remove them.

File: gulpfile.js/changelog.js (hunk 4 above)
Comment (RunDevelopment) [reply gulpfile.js/changelog.js]: I wasn't sure whether `slice` uses the iterator under the hood but apparently, it doesn't.
So, will do.

File: gulpfile.js/index.js (hunk 1 above)
Comment (RunDevelopment) [reply gulpfile.js/index.js]: I also like that all commands are visible at the bottom. This is basically a tradeoff between reducing redundancies and readability.

With the current style, you can see all tasks but have to write the name of each task 3 times (declaration at the source file + import here + export).
With the new style, you have to look at other source files to see all exported tasks but you only have to write the name of each task once.

So, what's better?
I actually don't mind either, so please decide.

File: gulpfile.js/changelog.js (hunk 6 above)
Comment (RunDevelopment) [reply gulpfile.js/changelog.js]: Yes and no.
When looking at where I used this function, you'll see that I always checked whether `components.json` was changed. I just assume that all changes in Autoloader & Show language are caused by the generated part of these files. This assumption isn't necessarily true but most of the time it is.

Only `addedComponent` and `changedComponentOrCore` use `notPartlyGenerated`. So you would have to change Autoloader and add/modify a language definition for the two to incorrectly categorize your PR.

It is possible that the sorters (if you know a better name, I'll take it) put a commit in the wrong category but it will rarely happen. But that's also the worst thing that can happen. No commits will be lost.

And, as I said before:
_Careful review of the generated changelog is still necessary._

File: gulpfile.js/index.js (hunk 1 above)
Comment (mAAdhaTTah) [reply gulpfile.js/index.js]: All at the bottom imo

File: gulpfile.js/index.js [hunk 8]
```diff
@@ -172,101 +159,37 @@ async function languagePlugins() {
...
-	});
-}
-
 
 exports.watch = watchComponentsAndPlugins;
 exports.default = parallel(components, plugins, componentsJsonToJs, build);
-exports.premerge = gitChanges;
+exports.premerge = premerge;
 exports.linkify = linkify;
 exports.changes = changes;
```
Comment (RunDevelopment) [inline gulpfile.js/index.js]: Just an idea: I want to avoid having to write the name of some tasks twice, so how about this:

```js
module.exports = {
    watch: watchComponentsAndPlugins,
    default: parallel(components, plugins, componentsJsonToJs, build),
    premerge,
    linkify,
    changes
};
```

This would also force us to specify all exported tasks in one place.

File: gulpfile.js/index.js (hunk 1 above)
Comment (RunDevelopment) [reply gulpfile.js/index.js]: Alright!

File: gulpfile.js/index.js (hunk 8 above)
Comment (mAAdhaTTah) [reply gulpfile.js/index.js]: That works. I'm not overly concerned about it, so pick a style you like and let's get this in!
